---
title: "quality_controls"
author: "Rubén Rellán Álvarez"
date: "20/10/2017"
output: html_document
---

Load the packages that we wil use.
```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(magrittr)
library(readr)
library(tidyverse)
library(ggfortify)
library(cowplot)
library(sparkline)
library(ggQC)
library(cvequality)
```

Embed plots, for example:

```{r}
# read in the raw data

qc <- read_csv("data/qc.csv")

qc <- qc[, 2:179]

qc[ , "dataset"] <- c("qcs")

qc <- qc[, c(1, 179, 2:178)]

samples <- read_csv("data/data_dev_stages.csv")

samples[ , "dataset"] <- c("samples_")

samples <- samples[, c(1, 190, 13:189)]


qc_long <- qc %>%
  gather(metabolite, intensity, -pool_id)

qc %>%
  ggplot(aes(x = pool_id, y = LPC_18_3)) +
               geom_point() + geom_line() + 
               stat_QC(method = "XmR")
  


#some summary analysis

qc_variance <- qc %>%
  summarise_each(funs(var))

qc_variance_t <- t(qc_variance)

qc_variance_t <- qc_variance_t [3:179, ]

qc_variance_t <- as.data.frame(qc_variance_t)

samples_variance <- samples %>%
  summarise_each(funs(var))

samples_variance_t <- t(samples_variance)
samples_variance_t <- samples_variance_t [3:179, ]
samples_variance_t <- as.data.frame(samples_variance_t)

write.csv(qc_variance_t, "output/qc_variance_t.csv")
write.csv(samples_variance_t, "output/samples_variance_t.csv")

# files modified externally

qc_variance_ready <- read_csv("output/qc_variance_t.csv")
samples_variance_ready <- read_csv("output/samples_variance_t.csv")

variance_data <- qc_variance_ready %>%
  inner_join(samples_variance_ready, by = "metabolite")

variance_data <- variance_data %>%
  mutate(F_statistic = samples_variance_samples^2 / qc_variance_qc^2)

co.var <- function(x) (100*sd(x)/mean(x))

qc_covar <- qc %>%
  summarise_each(funs(co.var))



qc_variance_t <- t(qc_variance)
qc_variance_t <- qc_variance_t [2:171, ]
qc_variance_t <- as.data.frame(qc_variance_t)
qc_variance_t <- qc_variance_t$qc
write_csv(qc_variance_t, "output/qc_covar_t.csv")

qc_covar_t <- t(qc_covar)

qc_covar_t <- qc_covar_t [2:171, ]

qc_covar_t <- as.data.frame(qc_covar_t)

colnames(qc_covar_t) <- c("covar")

write_csv(qc_covar_t, "output/qc_covar_t.csv")

```


Testing CV equality between samples and qcs 

```{r}
# we first load a dataframe where samples and qcs are combined

comb_qc_samples <- read_csv("data/qc_samples_combined.csv")

# We then use the ´cvequality´ package to calculate cv equality. To do this we first creat a function that will allow us to cycle over all the variables


mslr_test_qc <- function(x) {
  with(comb_qc_samples,
  mslr_test(nr = 1e4, 
               x, dataset))
  
}

# we then use the apply function. 

mslr_test_samples <- apply(comb_qc_samples[,3:179], 2, mslr_test_qc)

# the output is a nested list with mslr and p values for each compounds. We convert this list into a dataframe using the rbidlist functionfro the data.table package

mslr_test_samples_df <- rbindlist(mslr_test_samples, fill=TRUE)

# Finally we add the compound names to the dataframe

list <- colnames(comb_qc_samples[, 3:179])

mslr_test_samples_df$compound <- list

setDF(mslr_test_samples_df)

mslr_test_samples_df <- mslr_test_samples_df[, c(3, 2, 1)]

write_csv(mslr_test_samples_df, "output/mslr_test_samples_df.csv")

# we filter variables that have a p value > 0.001 

mslr_test_samples_df_filtered <- mslr_test_samples_df %>%
  filter(p_value < 0.001 )

write_csv(mslr_test_samples_df_filtered, "output/mslr_test_samples_df_filtered.csv")

```



